name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c  # v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest ruff mypy types-requests types-networkx pandas-stubs
        
    - name: Lint with Ruff
      run: |
        ruff check .
        
    - name: Type check with Mypy
      run: |
        mypy chaintrace
        
    - name: Run Tests
      # We skip integration tests that require API keys if env var is missing
      run: |
        pytest
